###############################################
#            Announcements Config!            #
###############################################

####################
# Tips:
#
# Use "§" To Color The Text !
# Use \n To Writte In The Next Line!
#
####################

# The interval ! The Amount Of Time Between Two Messages, (in ticks) 
# 20 ticks = 1 sec

interval: 1200

# The Messages ! A Bunch Of Texts That The Server chosses a random one of and broadcasts it!

# The Plugin Cruentlly has  messages , i'm planning on making the amount of messages customaisble !

# Message Number 1
msg1:"§a Msg1
# Message Number 2
msg2: "§a Msg2"
# Message Number 3
msg3: "§a Msg3"
# Message Number 4
msg4: "§a Msg4"
# Message Number 5
msg5: "§a Msg5"
# Message Number 6
msg6: "§a Msg6"
# Message Number 7
msg7: "§a Msg7"
# Message Number 8
msg8: "§a Msg8"
# Message Number 9
msg9: "§a Msg9"
# Message Number 10
msg10: "§a Msg10"
